#!/usr/bin/env python3
"""Generate every number and table the manuscript uses from committed
results/ artifacts (project rule: NO hand-typed numbers in the paper).

Outputs:
    paper/generated/numbers.tex   — \\newcommand macros used in prose
    paper/tables/*.tex            — booktabs table bodies \\input by main

Sources:
    results/detection/{summary.json,per_class_ap.csv,seed_stats.json}
    results/ablations/wire_method.csv
    results/benchmark/seed{0,1,2}/summary.json      (3-seed, if present)
    results/v5_stitch_crossover/summary.json        (current default run)

Rerun after any results change:
    python scripts/make_paper_tables.py
"""

from __future__ import annotations

import csv
import json
import statistics
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
GEN = ROOT / "paper" / "generated"
TAB = ROOT / "paper" / "tables"

# Which set of result directories to read. Every committed 512-px run was
# superseded when preprocess.target_size became 1024, and the two must
# never be mixed in one table — so the choice is made once, here, rather
# than path by path.
VARIANTS = {
    # benchmark_1024_final, not benchmark_1024: the latter is the working area
    # and still holds the pre-2026-07-30 runs, whose nGED was produced by the
    # timeout-truncated GED search and is not reproducible (see metrics.py).
    # The _final runs are on the deterministic bound AND on the current default
    # (bridge_span 7 + connectivity repair), and must not be mixed with the old
    # ones in a single table.
    "1024": {
        "detection": "results/detection_1024",
        "ablation": "results/ablations_1024/wire_method.csv",
        "default_run": "results/benchmark_1024_final/seed0",
        "seeds": "results/benchmark_1024_final",
        "oracle": "results/oracle_1024",
        "repair": "results/repair_1024",
        "stratified": "results/stratified_1024",
        "ports": "results/ports",          # templates are scale-invariant
    },
    "512": {
        "detection": "results/detection",   # numbers as cited; detection_512fixed reproduces them
        "ablation": "results/ablations/wire_method.csv",
        "default_run": "results/v5_stitch_crossover",
        "seeds": "results/benchmark",
        "oracle": "results/oracle",
        "repair": "results/repair",
        "stratified": "results/stratified",
        "ports": "results/ports",
    },
}
SRC = dict(VARIANTS["1024"])   # the adopted configuration

ABL_LABELS = {
    # csv label -> table row label (paper-facing)
    "v1_classical_directional": "classical (canny + directional snap)",
    "v2_newpreproc": "+ fixed preprocessing",
    "v3_ink_boundary_snap": "+ ink wires + boundary snap",
    "v4_plus_stitching": "+ mask-hole stitching",
    "v5_plus_crossover_DEFAULT": "+ crossover-aware nets (full)",
}

TOPO_COLS = [
    ("terminal_pair_f1", "term-pair $F_1$"),
    ("net_f1", "net $F_1$"),
    ("per_component_connected_acc", "per-comp.\\ acc."),
    ("nged", "nGED $\\downarrow$"),
    ("strict_success", "strict"),
]


def f3(x) -> str:
    return f"{float(x):.3f}"


def macro(name: str, value: str) -> str:
    return f"\\newcommand{{\\{name}}}{{{value}}}"


def load_ablation() -> list[dict]:
    with (ROOT / SRC["ablation"]).open() as fh:
        return list(csv.DictReader(fh))


def gen_numbers(abl: list[dict]) -> None:
    by_label = {r["label"]: r for r in abl}
    classical = by_label["v1_classical_directional"]
    v5 = by_label["v5_plus_crossover_DEFAULT"]
    # The ablation grew past v5. AblTpFOneVFive now means the v5 STAGE, which is
    # no longer the shipped configuration, so the prose must not use it as the
    # headline -- *Final* is the last row and follows the table automatically.
    final = abl[-1]

    det = json.loads((ROOT / SRC["detection"] / "summary.json").read_text())
    seed_stats_path = ROOT / SRC["detection"] / "seed_stats.json"
    if not seed_stats_path.exists():
        # a single-seed number must not be silently substituted for the
        # 3-seed mean+-std the manuscript reports
        raise SystemExit(
            f"missing {seed_stats_path}. Generate it with:\n"
            f"  ./venv/bin/python scripts/detector_comparison.py "
            f"--data data/yolo_1024/dataset.yaml --out-dir {SRC['detection']}")
    det_seeds = json.loads(seed_stats_path.read_text())
    s8 = det_seeds["yolov8s"]

    v5sum = json.loads(
        (ROOT / SRC["default_run"] / "summary.json").read_text()
    )
    rep = v5sum["repair"]

    lines = [
        "% AUTO-GENERATED by scripts/make_paper_tables.py — do not edit.",
        "% Regenerate after any results change.",
        macro("NumTestImages", str(v5sum["scored"])),
        *_support_macros(),
        *_oracle_macros(),
        *_repair_verify_macros(),
        macro("DetMapFifty", f3(s8["map50"]["mean"])),
        macro("DetMapFiftyStd", f"{s8['map50']['std']:.4f}"),
        macro("DetMapFiftyNinetyFive", f3(s8["map50_95"]["mean"])),
        macro("AblNetFOneClassical", f3(classical["net_f1"])),
        macro("AblNetFOneVFive", f3(v5["net_f1"])),
        macro("AblTpFOneClassical", f3(classical["terminal_pair_f1"])),
        macro("AblTpFOneVFive", f3(v5["terminal_pair_f1"])),
        macro("AblNetFOneFinal", f3(final["net_f1"])),
        macro("AblTpFOneFinal", f3(final["terminal_pair_f1"])),
        macro("AblStrictFinal", f3(final["strict_success"])),
        macro("AblStrictClassical", f3(classical["strict_success"])),
        macro("AblFinalLabel", final["label"].replace("_", " ")),
        macro("RepSolvBefore", f3(rep["solvable_before_rate"])),
        macro("RepSolvAfter", f3(rep["solvable_after_rate"])),
        macro("RepMeanAssumptions", f"{rep['mean_assumptions']:.1f}"),
        macro("RepMeanGauge", f"{rep['mean_gauge']:.1f}"),
        macro("RepSpiceValid", f3(rep["spice_valid_rate"])),
    ]
    (GEN / "numbers.tex").write_text("\n".join(lines) + "\n")
    print(f"wrote {GEN/'numbers.tex'} ({len(lines)-2} macros)")


def _signed(x: float) -> str:
    return f"{x:+.4f}"


def _support_macros() -> list[str]:
    """Test-split class supports, so the Dataset section can state its
    range without anyone typing a count."""
    p = ROOT / SRC["detection"] / "per_class_ap.csv"
    if not p.exists():
        return ["% per-class supports absent — run scripts/eval_detector.py"]
    with p.open() as fh:
        rows = [(r["class"], int(r["support"])) for r in csv.DictReader(fh)]
    lo = min(rows, key=lambda r: r[1])
    hi = max(rows, key=lambda r: r[1])
    return [
        macro("SupportMin", str(lo[1])),
        macro("SupportMinClass", lo[0]),
        macro("SupportMax", str(hi[1])),
        macro("SupportMaxClass", hi[0]),
        macro("NumClasses", str(len(rows))),
    ]


def _oracle_macros() -> list[str]:
    p = ROOT / SRC["oracle"] / "summary.json"
    if not p.exists():
        return ["% oracle results absent — run scripts/oracle.py"]
    s = json.loads(p.read_text())
    a = s["attribution_tp_f1"]
    return [
        macro("OracleDetection", _signed(a["detection"])),
        macro("OracleWires", _signed(a["wires"])),
        macro("OracleSnapping", _signed(a["snapping"])),
        macro("OracleNValid", str(s["n_mode_c_valid"])),
    ]


def _repair_verify_macros() -> list[str]:
    p = ROOT / SRC["repair"] / "summary.json"
    if not p.exists():
        return ["% repair results absent — run scripts/benchmark_repair.py"]
    s = json.loads(p.read_text())
    out = [
        macro("RepLiftCiLo", f3(s["lift_ci95_lo"])),
        macro("RepLiftCiHi", f3(s["lift_ci95_hi"])),
        macro("RepRegressed", str(s["regressed_images"])),
    ]
    if "topology_violations" in s:
        out += [
            macro("RepTopoViolations", str(s["topology_violations"])),
            macro("RepVerifiedImages", str(s["verified_images"])),
        ]
    if s.get("ground_accuracy_gauge_gnd_symbol_resolved") is not None:
        out += [
            macro("GroundAccResolved",
                  f3(s["ground_accuracy_gauge_gnd_symbol_resolved"])),
            macro("GroundAccStrict",
                  f3(s["ground_accuracy_gauge_gnd_symbol_strict"])),
            macro("GroundNGnd", str(s["ground_n_gauge_gnd_symbol"])),
        ]
    return out


def gen_port_table() -> None:
    p = ROOT / SRC["ports"] / "template_accuracy.json"
    if not p.exists():
        print(f"skip port table: {SRC['ports']}/template_accuracy.json absent")
        return
    acc = json.loads(p.read_text())
    out = [
        "% AUTO-GENERATED by scripts/make_paper_tables.py — do not edit.",
        "\\begin{tabular}{lrcccc}",
        "\\toprule",
        "& & \\multicolumn{2}{c}{oracle pose} & "
        "\\multicolumn{2}{c}{axis only} \\\\",
        "\\cmidrule(lr){3-4}\\cmidrule(lr){5-6}",
        "class & crops & median & $\\le$0.10 & median & $\\le$0.10 \\\\",
        "\\midrule",
    ]
    for cls, a in sorted(acc.items()):
        o, x = a["oracle_pose"], a["axis_only"]
        out.append(
            f"{cls} & {a['n_crops']} & {o['median_norm_err']:.3f} & "
            f"{o['frac_within_0.10'] * 100:.0f}\\% & "
            f"{x['median_norm_err']:.3f} & "
            f"{x['frac_within_0.10'] * 100:.0f}\\% \\\\"
        )
    out += ["\\bottomrule", "\\end{tabular}"]
    (TAB / "port_templates.tex").write_text("\n".join(out) + "\n")
    print(f"wrote {TAB/'port_templates.tex'} ({len(acc)} classes)")


def gen_stratified_table() -> None:
    p = ROOT / SRC["stratified"] / "stratified.csv"
    if not p.exists():
        print("skip stratified table: run scripts/analyze_failures.py")
        return
    with p.open() as fh:
        rows = list(csv.DictReader(fh))
    out = [
        "% AUTO-GENERATED by scripts/make_paper_tables.py — do not edit.",
        "\\begin{tabular}{lrcccc}",
        "\\toprule",
        "stratum & $n$ & term-pair $F_1$ & net $F_1$ & per-comp. & strict \\\\",
        "\\midrule",
    ]
    for r in rows:
        label = r["stratum"].replace("<=", "$\\le$").replace(">", "$>$")
        out.append(
            f"{label} & {r['n_images']} & {float(r['terminal_pair_f1']):.3f} & "
            f"{float(r['net_f1']):.3f} & "
            f"{float(r['per_component_connected_acc']):.3f} & "
            f"{float(r['strict_success']):.3f} \\\\"
        )
        if r["stratum"] == "all":
            out.append("\\midrule")
    out += ["\\bottomrule", "\\end{tabular}"]
    (TAB / "stratified.tex").write_text("\n".join(out) + "\n")
    print(f"wrote {TAB/'stratified.tex'} ({len(rows)} strata)")


def gen_detection_table() -> None:
    with (ROOT / SRC["detection"] / "per_class_ap.csv").open() as fh:
        rows = list(csv.DictReader(fh))
    out = [
        "% AUTO-GENERATED by scripts/make_paper_tables.py — do not edit.",
        "\\begin{tabular}{lrrr}",
        "\\toprule",
        "class & support & AP@0.5 & AP@0.5:0.95 \\\\",
        "\\midrule",
    ]
    for r in rows:
        out.append(
            f"{r['class']} & {r['support']} & {f3(r['ap50'])} & "
            f"{f3(r['ap50_95'])} \\\\"
        )
    out += ["\\bottomrule", "\\end{tabular}"]
    (TAB / "detection_per_class.tex").write_text("\n".join(out) + "\n")
    print(f"wrote {TAB/'detection_per_class.tex'} ({len(rows)} classes)")


def gen_ablation_table(abl: list[dict]) -> None:
    out = [
        "% AUTO-GENERATED by scripts/make_paper_tables.py — do not edit.",
        "\\begin{tabular}{l" + "c" * len(TOPO_COLS) + "}",
        "\\toprule",
        "configuration & "
        + " & ".join(h for _, h in TOPO_COLS)
        + " \\\\",
        "\\midrule",
    ]
    for r in abl:
        if r["label"] not in ABL_LABELS:
            continue  # crossover-null side branches: narrated, not tabled
        cells = []
        for key, _ in TOPO_COLS:
            if r.get(key):
                cells.append(
                    f"{f3(r[key])} [{f3(r[key + '_ci95_lo'])}, "
                    f"{f3(r[key + '_ci95_hi'])}]"
                )
            else:
                cells.append("--")
        out.append(f"{ABL_LABELS[r['label']]} & " + " & ".join(cells) + " \\\\")
    out += ["\\bottomrule", "\\end{tabular}"]
    (TAB / "wire_method_ablation.tex").write_text("\n".join(out) + "\n")
    print(f"wrote {TAB/'wire_method_ablation.tex'}")


def gen_3seed_table() -> None:
    seed_dirs = sorted((ROOT / SRC["seeds"]).glob("seed*"))
    summaries = []
    for d in seed_dirs:
        p = d / "summary.json"
        if p.exists():
            summaries.append(json.loads(p.read_text()))
    out = ["% AUTO-GENERATED by scripts/make_paper_tables.py — do not edit."]
    if len(summaries) < 2:
        out.append(
            "% 3-seed results not present yet — run scripts/benchmark.py "
            f"per seed into {SRC['seeds']}/seed<N>/."
        )
        out.append("\\multicolumn{2}{c}{\\emph{3-seed run pending}}")
    else:
        out += [
            "\\begin{tabular}{lc}",
            "\\toprule",
            f"metric & mean $\\pm$ std ({len(summaries)} seeds) \\\\",
            "\\midrule",
        ]
        for key, header in TOPO_COLS:
            vals = [s["topology"][key]["mean"] for s in summaries]
            mean = statistics.mean(vals)
            std = statistics.stdev(vals) if len(vals) > 1 else 0.0
            out.append(f"{header} & {mean:.3f} $\\pm$ {std:.3f} \\\\")
        for key, header in [
            ("solvable_before_rate", "DC-solvable (before repair)"),
            ("solvable_after_rate", "DC-solvable (after repair)"),
        ]:
            vals = [s["repair"][key] for s in summaries]
            mean = statistics.mean(vals)
            std = statistics.stdev(vals) if len(vals) > 1 else 0.0
            out.append(f"{header} & {mean:.3f} $\\pm$ {std:.3f} \\\\")
        out += ["\\bottomrule", "\\end{tabular}"]
    (TAB / "benchmark_3seed.tex").write_text("\n".join(out) + "\n")
    print(f"wrote {TAB/'benchmark_3seed.tex'} ({len(summaries)} seeds found)")


def gen_repair_table() -> None:
    v5 = json.loads((ROOT / SRC["default_run"] / "summary.json").read_text())
    rep = v5["repair"]
    rows = [
        ("SPICE syntactic validity", f3(rep["spice_valid_rate"])),
        ("DC-solvable before repair", f3(rep["solvable_before_rate"])),
        ("DC-solvable after repair", f3(rep["solvable_after_rate"])),
        ("mean ledger entries / circuit (assumption)", f"{rep['mean_assumptions']:.1f}"),
        ("mean ledger entries / circuit (gauge)", f"{rep['mean_gauge']:.1f}"),
    ]

    # topology preservation and gauge accuracy come from the dedicated
    # repair evaluation, which recomputes them per image rather than
    # asserting the invariant
    rp = ROOT / SRC["repair"] / "summary.json"
    if rp.exists():
        r = json.loads(rp.read_text())
        rows.append((
            "solvability lift (paired bootstrap 95\\% CI)",
            f"{r['solvability_lift']:.3f} "
            f"[{r['lift_ci95_lo']:.3f}, {r['lift_ci95_hi']:.3f}]",
        ))
        rows.append(("circuits made worse by repair", str(r["regressed_images"])))
        if "topology_violations" in r:
            rows.append((
                "topology changed by repair",
                f"{r['topology_violations']} / {r['verified_images']}",
            ))
        if r.get("ground_accuracy_gauge_gnd_symbol_resolved") is not None:
            rows.append((
                "ground-choice accuracy, GND symbol present",
                f"{r['ground_accuracy_gauge_gnd_symbol_resolved']:.3f} "
                f"($n$={r['ground_n_gauge_gnd_symbol']}, decidable cases)",
            ))
        if r.get("ground_n_assumed"):
            rows.append((
                "ground-choice accuracy, no GND symbol",
                f"{r['ground_accuracy_assumed_strict']:.3f} "
                f"($n$={r['ground_n_assumed']})",
            ))

    out = [
        "% AUTO-GENERATED by scripts/make_paper_tables.py — do not edit.",
        "\\begin{tabular}{lc}",
        "\\toprule",
    ]
    out += [f"{name} & {val} \\\\" for name, val in rows]
    out += ["\\bottomrule", "\\end{tabular}"]
    (TAB / "repair_summary.tex").write_text("\n".join(out) + "\n")
    print(f"wrote {TAB/'repair_summary.tex'}")


def main() -> None:
    import argparse
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--variant", choices=sorted(VARIANTS), default="1024",
                    help="which result set to read (default: 1024, the "
                         "adopted configuration). 512 runs are superseded "
                         "and must not be mixed with 1024 numbers.")
    args = ap.parse_args()
    SRC.clear(); SRC.update(VARIANTS[args.variant])
    print(f"variant={args.variant}: reading {SRC['default_run']}")

    GEN.mkdir(parents=True, exist_ok=True)
    TAB.mkdir(parents=True, exist_ok=True)
    abl = load_ablation()
    gen_numbers(abl)
    gen_detection_table()
    gen_ablation_table(abl)
    gen_3seed_table()
    gen_repair_table()
    gen_port_table()
    gen_stratified_table()


if __name__ == "__main__":
    main()
