#!/usr/bin/env python3
"""Sweep one config parameter on the REAL benchmark, then cross-validate it.

Every tuned value in this pipeline was picked either on a proxy metric, at 512
px, or under a masking regime that no longer exists -- and the two checked so far
were both wrong. bridge_span was ELEVEN points off optimum with a significant
gain unclaimed; snapping.max_expand peaked at 80 rather than 60. So the remaining
parameters are not safe to assume, and a benchmark now costs ~75 s (removing the
timeout-truncated GED search took it from ~35 min), which makes sweeping them on
the actual objective cheaper than the proxies used to be.

Does three things so a sweep cannot be reported dishonestly:

  runs      generates one config per value by deep-setting a dotted key into the
            loaded default, so nothing else can drift between arms
  tabulates every metric, not just the selection one, because a parameter that
            buys terminal-pair F1 by welding nets shows up as per-component or
            strict going the other way
  selects   by 10-fold cross-validation via cv_select_param.py, because a peak
            read off 190 images is partly noise even when those images are the
            validation split and not the reported one

It defaults to --split val (--gt-dir data/gt_val_1024) and scoring test takes
saying so. Selection must not touch the split it is reported on; the two splits
swapped names on 2026-08-03 for exactly that reason (data/README.md).

Usage:
    python scripts/sweep_param.py detect.confidence 0.2 0.3 0.4 0.5 0.6
    python scripts/sweep_param.py wires.min_blob_area 20 40 80 160 --jobs 3
    python scripts/sweep_param.py nodes.connectivity 4 8 --metric strict_success
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
CFG_DIR = ROOT / "scratchpad" / "sweeps"
OUT_ROOT = ROOT / "results" / "sweeps_bench"


def coerce(s: str):
    """'8' -> 8, '0.4' -> 0.4, 'true' -> True, 'band' -> 'band'."""
    low = s.lower()
    if low in ("true", "false"):
        return low == "true"
    if low in ("none", "null"):
        return None
    for cast in (int, float):
        try:
            return cast(s)
        except ValueError:
            pass
    return s


def deep_set(d: dict, dotted: str, value) -> None:
    keys = dotted.split(".")
    node = d
    for k in keys[:-1]:
        if k not in node or not isinstance(node[k], dict):
            raise SystemExit(f"no such config section: {'.'.join(keys[:-1])!r}")
        node = node[k]
    if keys[-1] not in node:
        raise SystemExit(
            f"{dotted!r} is not an existing key -- refusing to invent one, "
            f"since a typo would silently sweep nothing")
    node[keys[-1]] = value


def slug(v) -> str:
    return str(v).replace(".", "p").replace("-", "m")


def main() -> None:
    ap = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("key", help="dotted config key, e.g. detect.confidence")
    ap.add_argument("values", nargs="+")
    ap.add_argument("--jobs", type=int, default=3,
                    help="concurrent benchmarks; 8 exhausted the disk once")
    ap.add_argument("--metric", default="terminal_pair_f1")
    ap.add_argument("--folds", type=int, default=10)
    ap.add_argument("--config", default=None)
    ap.add_argument("--reuse", action="store_true",
                    help="skip values whose run directory already has a summary")
    # A sweep selects a parameter, so it must never touch the split that
    # parameter is then reported on — that circularity is what the validation
    # annotation exists to break. Both defaults therefore point at val, and
    # scoring test takes an explicit --split test.
    ap.add_argument("--split", default="val")
    ap.add_argument("--splits-dir", default=None)
    ap.add_argument("--gt-dir", default="data/gt_val_1024")
    ap.add_argument("--no-spice", action="store_true",
                    help="skip ngspice; topology metrics are unaffected")
    args = ap.parse_args()

    sys.path.insert(0, str(ROOT / "src"))
    from schematic2netlist.config import load_config

    base = load_config(args.config)
    vals = [coerce(v) for v in args.values]
    CFG_DIR.mkdir(parents=True, exist_ok=True)
    tag = args.key.replace(".", "_")

    jobs = []
    for v in vals:
        cfg = json.loads(json.dumps(base))       # deep copy, no aliasing
        deep_set(cfg, args.key, v)
        cp = CFG_DIR / f"{tag}__{slug(v)}.yaml"
        cp.write_text(
            f"# GENERATED by scripts/sweep_param.py: {args.key} = {v!r}\n"
            f"# Everything else is the loaded default, so arms differ in one key.\n"
            + yaml.safe_dump(cfg, sort_keys=False))
        out = OUT_ROOT / tag / slug(v)
        jobs.append((v, cp, out))

    # A key whose stage's output is CACHED cannot take effect, and the sweep
    # would report a perfectly flat curve that reads as "no effect" when the
    # experiment never ran. Both traps are real: detect.confidence looked flat
    # below 0.4 because the cache was written with that threshold already
    # applied (minimum confidence in it is 0.4118), and every preprocess.* key
    # is inert because frames are pre-generated into preprocess.images_dir.
    root = args.key.split(".")[0]
    if root == "preprocess" and args.key not in ("preprocess.images_dir",):
        print(f"[REFUSING] {args.key} cannot take effect: frames are "
              f"pre-generated into {base['preprocess']['images_dir']}, and the "
              f"benchmark reads them rather than re-running preprocessing.\n"
              f"  Regenerate frames per value first (scripts/preprocess.py with "
              f"a per-value images_dir), then sweep preprocess.images_dir.")
        raise SystemExit(2)
    if root == "detect":
        cdir = Path(base["detect"]["cache_dir"])
        lows = []
        for f in list(cdir.glob("*.json"))[:40]:
            try:
                lows += [d.get("confidence", 1.0)
                         for d in json.loads(f.read_text())["detections"]]
            except Exception:
                pass
        if lows and args.key == "detect.confidence":
            floor = min(lows)
            below = [v for v in vals if isinstance(v, (int, float)) and v < floor]
            if below:
                print(f"[WARNING] {cdir} has minimum confidence {floor:.4f}, so "
                      f"values {below} cannot explore anything -- the threshold "
                      f"was baked in when the cache was written. Regenerate the "
                      f"cache at a lower confidence first.\n")

    print(f"sweeping {args.key} over {vals}  ({args.jobs} at a time)\n")
    pending = [(v, c, o) for v, c, o in jobs
               if not (args.reuse and (o / "summary.json").exists())]
    for i in range(0, len(pending), args.jobs):
        batch = pending[i:i + args.jobs]
        procs = []
        for v, c, o in batch:
            o.mkdir(parents=True, exist_ok=True)
            log = open(o / "bench.log", "w")
            procs.append((v, subprocess.Popen(
                [str(ROOT / "venv/bin/python"), str(ROOT / "scripts/benchmark.py"),
                 "--config", str(c), "--out-dir", str(o)]
                + (["--split", args.split] if args.split else [])
                + (["--splits-dir", args.splits_dir] if args.splits_dir else [])
                + (["--gt-dir", args.gt_dir] if args.gt_dir else [])
                + (["--no-spice"] if args.no_spice else []),
                stdout=log, stderr=subprocess.STDOUT, cwd=ROOT)))
        for v, p in procs:
            rc = p.wait()
            print(f"  {args.key}={v}: {'ok' if rc == 0 else f'FAILED rc={rc}'}",
                  flush=True)

    rows = []
    for v, _c, o in jobs:
        p = o / "summary.json"
        if not p.exists():
            rows.append((v, None))
            continue
        t = json.loads(p.read_text()).get("topology", {})
        g = lambda k: ((t.get(k) or {}).get("mean")
                       if isinstance(t.get(k), dict) else t.get(k))
        rows.append((v, {"tp": g("terminal_pair_f1"), "net": g("net_f1"),
                         "pc": g("per_component_connected_acc"),
                         "st": g("strict_success"), "ng": g("nged")}))

    shipped = base
    for k in args.key.split("."):
        shipped = shipped[k]
    print(f"\n{args.key}  (shipped: {shipped!r})")
    print(f"{'value':>10s} {'tp_f1':>8s} {'net_f1':>8s} {'percomp':>8s} "
          f"{'strict':>8s} {'nGED':>8s}")
    best = (None, -1.0)
    for v, m in rows:
        if m is None:
            print(f"{str(v):>10s}   FAILED")
            continue
        if m["tp"] > best[1]:
            best = (v, m["tp"])
        mark = "  <- shipped" if v == shipped else ""
        print(f"{str(v):>10s} {m['tp']:8.4f} {m['net']:8.4f} {m['pc']:8.4f} "
              f"{m['st']:8.4f} {m['ng']:8.4f}{mark}")
    print(f"\n  best terminal-pair F1 at {best[0]!r} ({best[1]:.4f})")

    ok = [(v, o) for (v, _c, o), (_v, m) in zip(jobs, rows) if m is not None]
    if len(ok) >= 2:
        cmd = [str(ROOT / "venv/bin/python"),
               str(ROOT / "scripts/cv_select_param.py"),
               "--metric", args.metric, "--folds", str(args.folds),
               "--out", str(ROOT / f"results/sweeps/cv_{tag}.json")]
        cmd += [f"{v}={o}" for v, o in ok]
        print()
        subprocess.run(cmd, cwd=ROOT)


if __name__ == "__main__":
    main()
